---

# AWS Credentials
aws_access_key: ""
aws_secret_key: ""
aws_region:     "ap-south-1"

# VPC Information
vpc_name:       "uat"
vpc_cidr_block: "10.20.0.0/16"

# For Security Group Rule
my_ip: ""

# Subnets
public_subnet_1_cidr:  "10.20.0.0/24"
private_subnet_1_cidr: "10.20.1.0/24"

#Details for Launching EC2
environment: "uat"
public_ec2_type:
 - {instance_type: 't2.micro' ,ami: 'ami-d783a9b8' ,count: '1' ,device_name: '/dev/sdb' ,volume_size: '10', name: 'web01'}

private_ec2_type:
 - {instance_type: 't2.micro' ,ami: 'ami-d783a9b8' ,count: '1' ,device_name: '/dev/sdb' ,volume_size: '10', name: 'app01'}
