---
- name: Copy private key to bastion/webServer launched above
  copy:
    src: files/id_rsa
    dest: /home/ec2-user/.ssh/id_rsa
    owner: ec2-user
    group: ec2-user
    mode: 0400

- name: Install ansible on launched webServer
  shell: 'pip install ansible'

- name: Install nginx
  shell: 'amazon-linux-extras install nginx1.12'

- name: Copy default.conf
  template:
    src: templates/default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    owner: nginx
    group: nginx

- name: Copy ssl certificate
  copy:
    src: files/myssl.crt
    dest: /etc/ssl/certs/myssl.crt

- name: Copy ssl key
  copy:
    src: files/myssl.key
    dest: /etc/ssl/private/myssl.key

- name: Validate nginx configuration
  shell: "nginx -t"

- name: Start nginx
  service:
    name: nginx
    state: started
