---

- name: create key pair using key_material obtained using 'file' lookup plugin
  ec2_key:
    name: my_keypair
    key_material: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"

- name: Launching an EC2 Instance
  ec2:
    instance_type: "{{ item.instance_type }}"
    image: "{{ item.ami }}"
    region: "{{ item.region }}"
    keypair: "my_keypair"
    count: "{{ item.count }}"
    # instance_profile_name: "{{ item.instance_profile_name }}"
    group_id: "{{ item.security_group }}"
    vpc_subnet_id: "{{ item.subnet_id }}"
    wait: true
    volumes:
      - device_name: "{{ item.device_name }}"
        volume_size: "{{ item.volume_size }}"
    instance_tags:
     name: "{{ item.name }}"
     environment: "{{ environment }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: ec2
  with_items:
     - "{{ ec2_type }}"

- name: Waiting for the instance to come
  local_action: wait_for
  host: "{{ item.private_ip }}"
  state: started
  port: 22
  with_items: ec2.instance
