---

- name: create key pair using key_material obtained using 'file' lookup plugin
  ec2_key:
    name: my_keypair
    key_material: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"

- name: Launching an EC2 Instance in Private Subnet
  ec2:
    instance_type: "{{ item.instance_type }}"
    image: "{{ item.ami }}"
    region: "{{ aws_region }}"
    keypair: "my_keypair"
    count: "{{ item.count }}"
    group_id: "{{ app_sg_id }}"
    vpc_subnet_id: "{{ private_subnet_id }}"
    wait: true
    volumes:
      - device_name: "{{ item.device_name }}"
        volume_size: "{{ item.volume_size }}"
    instance_tags:
     name: "{{ item.name }}"
     environment: "{{ environment }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: private_ec2
  with_items:
     - "{{ private_ec2_type }}"

- debug:
   var: private_ec2.stdout

- name: Launching an EC2 Instance in public subnet
  ec2:
    instance_type: "{{ item.instance_type }}"
    image: "{{ item.ami }}"
    region: "{{ aws_region }}"
    keypair: "my_keypair"
    count: "{{ item.count }}"
    group_id: "{{ web_sg_id }}"
    vpc_subnet_id: "{{ public_subnet_id }}"
    wait: true
    volumes:
      - device_name: "{{ item.device_name }}"
        volume_size: "{{ item.volume_size }}"
    instance_tags:
     name: "{{ item.name }}"
     environment: "{{ environment }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    assign_public_ip : yes
  register: public_ec2
  with_items:
     - "{{ public_ec2_type }}"

- debug:
   var: public_ec2.stdout

# - name: Waiting for the instance to come
#   local_action: wait_for
#   host: "{{ item.public_ip }}"
#   state: started
#   port: 22
#   with_items: public_ec2.instance
